### ISSUE TITLE
Authentication token has expired

### ISSUE THREAD

**Issue by jdblischak** [TileDB-Inc/htslib-feedstock#12]
The recently merged bd0d62c599a7e048b614bc0d499039061293e3c8 from PR #10 failed to upload conda binaries to the tiledb channel because the anaconda.org token has expired

```
binstar_client.errors.Unauthorized: ('Authentication token has expired', 401)
```

https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=37004&view=results

**Comment by Shelnutt2** [comment]
The API token has been replaced.

**Comment by jdblischak** [comment]
I restarted the previously failed jobs from commit bd0d62c599a7e048b614bc0d499039061293e3c8

https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=37004&view=results

**Comment by jdblischak** [comment]
The restarted jobs are failing with the same error about an expired token. Maybe restarted jobs can't access updated variables?? Just in case I started a new job from the main branch:

https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=37230&view=results

**Comment by jdblischak** [comment]
Both the 3rd restart of the previous job and the brand new job I manually started today failed due to an expired token

**Comment by jdblischak** [comment]
@ihnorton copy-pasted the new token this afternoon and started a new build

https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=37303&view=results

And new binaries are being uploaded! 🎉 

https://anaconda.org/tiledb/htslib/files?version=1.16

![image](https://github.com/TileDB-Inc/htslib-feedstock/assets/1608317/43379a72-5528-4db5-bc49-1729d528b49e)

**Comment by ihnorton** [comment]
Thanks @jdblischak 🙇
